### ISSUE TITLE
Doesn't install for MIKE 2021

### ISSUE THREAD

**Issue by SirAdelaide** [DHI/NetCDF_Client#3]
I have MIKE Zero Release 2021 installed (demo mode as license hire has expired), but when I try to run DHI.Generic.NetCDF.MIKE.exe it says:

Unhandled Exception: System.Exception: Cannot find a proper MIKE installation
   at DHI.Generic.NetCDF.MIKE.NetCDFClient..ctor() in C:\Users\czc\Source\Repos\netcdf-client\NetCDFClient.cs:line 58
   at DHI.Generic.NetCDF.MIKE.Program.Main(String[] args) in C:\Users\czc\Source\Repos\netcdf-client\Program.cs:line 29

**Comment by gillianord** [comment]
I'm having the same problem. Were you ever able to sort it out?

**Comment by SirAdelaide** [comment]
No, I gave up and moved on to something else.

**Comment by gillianord** [comment]
Thanks for getting back to me at least haha. I found a python package called mikeio that seems to be able to convert netcdf to dfs. Just in case it could still be useful for you, it's on github.
https://github.com/DHI/mikeio

**Comment by dhiczc** [comment]
Sorry for the delay. The binaries are updated now.
